# https://taskfile.dev

version: '3'

includes:
  common: ../common

dotenv: ['.env', '.secrets', '../.env', '../.secrets']
env:
  GH_REPO: spring-music
  BUILD_SCRIPT: .github/scripts/build-app.sh
  SRC_DIR: sourcecode
  ARTIFACT_DIR: artifacts
  DOCKER_BUILD_IMAGE: ubuntu22.04:openjdk11
  BUILD_DIR: build/libs
  APP_VERSION: 2.0.0

tasks:
  build-app-gradle:
    cmds:
      - task: common:build-app

  publish-jar-gradle:
    deps: ['build-app-gradle']
    cmds:
      - mkdir -p $ARTIFACT_DIR
      - find $SRC_DIR/ -regextype posix-basic -regex  ".*$BUILD_DIR\/${GH_REPO}-${APP_VERSION}\.jar" -exec cp {} $ARTIFACT_DIR \;
      - sudo rm -rf $SRC_DIR
    generates:
      - $ARTIFACT_DIR/${GH_REPO}-${APP_VERSION}.jar

  build-push-docker-image-amazoncorretto:
    deps: ['publish-jar-gradle']
    cmds:
      - task: common:build-push-docker-image-java
        vars:
          DOCKER_DIR: "{{.SRC_DIR}}/{{.GH_REPO}}"
          DOCKERFILE_NAME: "Dockerfile.amazoncorretto-17-alpine3-15"
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: "{{.APP_VERSION}}-amazoncorretto-17-alpine3-15"

  build-push-docker-image-temurin:
    deps: ['publish-jar-gradle']
    cmds:
      - task: common:build-push-docker-image-java
        vars:
          DOCKER_DIR: "{{.SRC_DIR}}/{{.GH_REPO}}"
          DOCKERFILE_NAME: Dockerfile.eclipse-temurin-17-jre-jammy
          DOCKER_IMAGE_NAME: "{{.GH_REPO}}"
          DOCKER_IMAGE_TAG: ${APP_VERSION}-eclipse-temurin-17-jre-jammy
