# https://taskfile.dev

version: '3'

includes:
  common: ../common

dotenv: ['.env', '.secrets', '../.env', '../.secrets']
env:
  GH_REPO: spring-music
  BUILD_SCRIPT: .github/scripts/build-app.sh
  SRC_DIR: sourcecode
  ARTIFACT_DIR: artifacts
  DOCKER_BUILD_IMAGE: ubuntu22.04:openjdk11

tasks:
  prep:
    cmds:
      - task: common:git-clone
      - task: common:docker-login

  build-app:
    deps: ['prep']
    cmds:
      - docker run --rm -v `pwd`:/tmp/code $DOCKER_REGISTRY/$GH_ORG/$DOCKER_BUILD_IMAGE bash -c "cd /tmp/code/$SRC_DIR/$GH_REPO; bash $BUILD_SCRIPT"

  publish-jar:
    deps: ['build-app']
    cmds:
      - mkdir -p $ARTIFACT_DIR
      - find $SRC_DIR/ -regextype posix-basic -regex  ".*\/build\/libs\/$GH_REPO.*[0-9]\.[0-9]\.[0-9]\.jar" -exec cp {} $ARTIFACT_DIR \;
