# https://taskfile.dev

version: '3'

dotenv: ['.env', '.secrets', '../.env', '../.secrets']
env:
  DOCKER_DIR: ubuntu22.04-openjdk11
  DOCKER_IMAGE_NAME: ubuntu22.04
  DOCKER_IMAGE_TAG: openjdk11

tasks:
  docker-build:
    cmds:
      - cd $DOCKER_DIR; docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .

  docker-login:
    cmds:
      - echo $GH_PAT | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin

  docker-push:
    deps: ['docker-build','docker-login']
    cmds:
      - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_REGISTRY/$GH_ORG/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker push $DOCKER_REGISTRY/$GH_ORG/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

