# https://taskfile.dev

version: '3'

includes:
  common: ../../common

dotenv: ['.env', '.secrets', '../.env', '../.secrets', '../../.env', '../../.secrets']

tasks:
  default:
    cmds:
      - task: common:build-push-docker-image
        vars:
          DOCKER_IMAGE_NAME: alpine3.16
          DOCKER_IMAGE_TAG: openjdk17
