# https://taskfile.dev

version: '3'

tasks:
  git-clone:
    cmds:
      - sudo rm -rf $SRC_DIR; mkdir -p $SRC_DIR
      - cd $SRC_DIR; git clone https://github.com/$GH_ORG/$GH_REPO.git

  docker-build:
    cmds:
      - cd $DOCKER_DIR; docker buildx build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG . -f $DOCKERFILE_NAME

  docker-login:
    cmds:
      - echo $GH_PAT | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin

  docker-push:
    deps: ['docker-build','docker-login']
    cmds:
      - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_REGISTRY/$GH_ORG/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
      - docker push $DOCKER_REGISTRY/$GH_ORG/$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

