# https://taskfile.dev

version: '3'

tasks:
  git-clone:
    cmds:
      - sudo rm -rf $SRC_DIR; mkdir -p $SRC_DIR
      - cd $SRC_DIR; git clone https://github.com/$GH_ORG/$GH_REPO.git

  docker-login:
    cmds:
      - echo $GH_PAT | docker login $DOCKER_REGISTRY -u $DOCKER_USERNAME --password-stdin

  docker-build:
    cmds:
      - cd {{.DOCKER_DIR}}; docker buildx build -t {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} . -f {{.DOCKERFILE_NAME}}

  docker-push:
    cmds:
      - docker tag {{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}} $DOCKER_REGISTRY/$GH_ORG/{{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}}
      - docker push $DOCKER_REGISTRY/$GH_ORG/{{.DOCKER_IMAGE_NAME}}:{{.DOCKER_IMAGE_TAG}}

  build-app:
    deps: ['git-clone', 'docker-login']
    cmds:
      - docker run --rm -v `pwd`:/tmp/code $DOCKER_REGISTRY/$GH_ORG/$DOCKER_BUILD_IMAGE bash -c "cd /tmp/code/$SRC_DIR/$GH_REPO; bash $BUILD_SCRIPT"

  build-push-docker-image:
    cmds:
      - task: docker-login
      - task: docker-build
        vars:
          DOCKER_DIR: '{{.DOCKER_DIR}}'
          DOCKERFILE_NAME: '{{.DOCKERFILE_NAME}}'
          DOCKER_IMAGE_NAME: '{{.DOCKER_IMAGE_NAME}}'
          DOCKER_IMAGE_TAG: '{{.DOCKER_IMAGE_TAG}}'
      - task: docker-push
        vars:
          DOCKER_IMAGE_NAME: '{{.DOCKER_IMAGE_NAME}}'
          DOCKER_IMAGE_TAG: '{{.DOCKER_IMAGE_TAG}}'

  build-push-docker-image-java:
    cmds:
      - task: git-clone
      - mkdir -p $SRC_DIR/$GH_REPO/$BUILD_DIR
      - cp $ARTIFACT_DIR/${GH_REPO}-${APP_VERSION}.jar $SRC_DIR/$GH_REPO/$BUILD_DIR
      - task: docker-login
      - task: docker-build
        vars:
          DOCKER_DIR: '{{.DOCKER_DIR}}'
          DOCKERFILE_NAME: '{{.DOCKERFILE_NAME}}'
          DOCKER_IMAGE_NAME: '{{.DOCKER_IMAGE_NAME}}'
          DOCKER_IMAGE_TAG: '{{.DOCKER_IMAGE_TAG}}'
      - task: docker-push
        vars:
          DOCKER_IMAGE_NAME: '{{.DOCKER_IMAGE_NAME}}'
          DOCKER_IMAGE_TAG: '{{.DOCKER_IMAGE_TAG}}'
